### PR TITLE
Detached mosaicing tool

### PR DESCRIPTION
**Pull request by gigjozsa**
Please find a detached mosaicing tool in utils:
- detached
  - to do so, I kept a minimal rms calculator in the tool (just in case the user does not want to use two tools)
- some upgrading of functions
- pdf and other format output

### CODE REVIEW

**Review by SharmilaGoedhart — COMMENTED** [review]
Looks ok to me.  I can run it, and download as pdf, though the output is 24 pages long. 
I think a plot of the actual mosaic pointings and weights is more useful.  

It would also be nice to write out the pointings in a katpoint compatible csv file.  We'll be asking users up upload their pointings so that we can check for conflicts with other proposals and also assess LST over-subscription.

**Comment by gigjozsa** [comment]
@SharmilaGoedhart @spassmoor 

- There are three possible hard outputs in the code: statistics, pointing positions, csv file, pointing this out in the description now (obviously one can also produce a printed output in addition, but that's 24 pages)
- changed the output format of the ascii file into the OPT csv format

I do not know how to hide cells from being printed in a printed output. There are only a few cells that should be printed (the rest being code which can be hidden), which would then result in less than 24 pages. Any advise?

**Comment by SharmilaGoedhart** [comment]
@gigjozsa I don't think it is necessary to print out this entire notebook.  We really only want to see what went into the sensitivity calculator.  In this tool, the key output is the list of pointing centres, and the relative sensitivity coverage.

I have had a look at the output and it seems fine to me.

@spassmoor can you have a look and if happy, merge the pull request.  SimonR will then add this to the binder folder.

**Comment by o-smirnov** [comment]
This will hide cell code:

IPython.display import display, HTML, Javascript
display(Javascript("$('div.input').hide();"))

Replace with show() to show.

On Tue, Jun 16, 2020 at 7:19 PM Gyula Jozsa (Josh) <notifications@github.com>
wrote:
>
> @SharmilaGoedhart @spassmoor
>
> There are three possible hard outputs in the code: statistics, pointing
positions, csv file, pointing this out in the description now (obviously
one can also produce a printed output in addition, but that's 24 pages)
> changed the output format of the ascii file into the OPT csv format
>
> I do not know how to hide cells from being printed in a printed output.
There are only a few cells that should be printed (the rest being code
which can be hidden), which would then result in less than 24 pages. Any
advise?

**Review by spassmoor — APPROVED** [review]

**Comment by gigjozsa** [comment]
@o-smirnov implemented this. This is good for now, I will investigate how to toggle single cells. If you also know that, would of course be great. but will merge for now.

**Pull request merged**
