### PR TITLE
This is to fix the typo and a recommit

### PR DESCRIPTION
**Pull request by spassmoor**
Here is the  fixe typo for you to review

### CODE REVIEW

**Comment by gigjozsa** [comment]
I will suggest an updated version. Is anyone working on it right now?

**Comment by spassmoor** [comment]
No , go ahead

**Comment by gigjozsa** [comment]
@spassmoor @foxmouldy  , minor adjustments:
- Use astropy constants
- Issue warning re line width
- Minor beauty corrections
please inspect and approve.

**Comment by spassmoor** [comment]
@gigjozsa  I might modify this a bit because I think the inline equations $Sym_{bol}$ type of stuff breaks the pdf generation.

**Comment by gigjozsa** [comment]
@spassmoor hmm, I cannot reproduce this with my local installation:
[MeerKAT_Spectral_line_sensitivity_Calculator-1.pdf](https://github.com/ska-sa/MeerKAT-Cookbook/files/4824086/MeerKAT_Spectral_line_sensitivity_Calculator-1.pdf)

**Comment by gigjozsa** [comment]
@spassmoor are you currently working on it? I would like to implement @foxmouldy's suggestion to relate the last and the second-last box.

**Comment by spassmoor** [comment]
go ahead , I am not working on it

**Comment by gigjozsa** [comment]
@spassmoor as said pdf is generated correctly, so I cannot work on that. Instead of pushing a suggestion here I created an alternative pull request #15 . The reviewers can then choose whichever they like best.

**Comment by spassmoor** [comment]
@gigjozsa  This fine

**Pull request merged**
