### PR TITLE
Add sensitivity calculator

### PR DESCRIPTION
**Pull request by sratcliffe**
This is a cleanup merge before referencing the sensitivity calculator properly in the service desk.

### CODE REVIEW

**Review by rubyvanrooyen — CHANGES_REQUESTED** [review]
Please help me to tailor my feedback, since I have been out of the loop with this one

What is the purpose of this notebook? As example python code or as a user level interactive notebook?

The installation instructions at the top, are those only for this notebook or in general?
Should that rather be moved to a README and the purpose summarised?

The code blocks a little difficult to read and follow, could you please PEP8 the coding blocks which will make it easier to give comments since inline comments are not a thing for notebooks

**Comment by sratcliffe** [comment]
This is just a place to host the IPython notebook built by commissioning as a sensitivity calculator. This gets used by binder to display a live version of the most up to date calculator for end users to use. 

The intent of the PR wasn't really to review the notebook itself, rather just to bring this branch into master before open time begins. 

Perhaps it is easier to just make a new repo to hold the calculator by itself ?

**Comment by SharmilaGoedhart** [comment]
There is still a stray line referencing "Justin's spreadsheet" which needs to be removed. As far as I know we have updated the Tsys/Eta to use values derived by Sean using the full array.

**Comment by SharmilaGoedhart** [comment]
@spassmoor can you confirm that the Tsys/Eta values have been updated and that the reference to Justin's spreadsheet is no longer relevant?

**Comment by rubyvanrooyen** [comment]
Aaa, that explains everything.

In that case I do not believe a pull request is needed.
May I suggest options:
0 - directly merge the branch
1 - rather request TomM or SeanP to review the pull request to quickly double check the functionality before merge

**Comment by sratcliffe** [comment]
Indeed - doing a PR->merge is just a habit :) I should have explained before that it wasn't a proper "review"...

**Comment by rubyvanrooyen** [comment]
Programmers and their bad habits :)
We do not need the review process here, as soon as commissioning is satisfied, just merge

**Comment by spassmoor** [comment]
Yes , I can confirm that the tsys values are the new ones

**Comment by SharmilaGoedhart** [comment]
I'm glad you did do a pull request - I've been trying to make those old values from Justin disappear off the web for the past two years!  That link is still live.

**Comment by sratcliffe** [comment]
That is the end of the Justin spreadsheet - erase from existence.

**Pull request merged**
