### PR TITLE
Change fpdf dependency to optional

### PR DESCRIPTION
**Pull request by gigjozsa**
… immediately if it is not installed

### CODE REVIEW

**Comment by gigjozsa** [comment]
@sratcliffe can we add additional requirements in binder/requirements.txt or where can we add dependencies?

**Comment by spassmoor** [comment]
@gigjozsa  This package is not in the container that is part of the on-line system. If you need pdfs consider using the matplotlib pdfPages. https://matplotlib.org/3.1.0/gallery/misc/multipage_pdf.html

**Comment by gigjozsa** [comment]
@spassmoor the other option would be to add the package to the container in the online-system I guess.

**Comment by gigjozsa** [comment]
@spassmoor @sratcliffe could you add fpdf to the online system?

**Comment by foxmouldy** [comment]
Oh sorry I've just seen this. I'll remove my "issue".

**Comment by gigjozsa** [comment]
@spassmoor @foxmouldy @SharmilaGoedhart there seem to be requirements that I am not aware of. In order to prevent further potential system conflicts could perhaps someone with the required knowledge take over for the system integration (I will of course answer any question) or give me precise instructions, e.g.:

- how does the user know which packages to install? One might argue that the software should rely on common standard packages, but what are these? We could make a centralised requirements.txt available where we can put our requirements, (provided they are accessible via pyPI) and tell the user to install these via pip. Where should/does this file reside?

- How can the user access files from the online system (see https://github.com/ska-sa/MeerKAT-Cookbook/issues/21#issuecomment-650186042)?

- How does the online system get cleaned up (how are files deleted after using it)?

- How is the online system supposed to work, what is its functionality (sorry for the generic question)?

- What are the precise requirements for the notebooks (e.g. no files written to disk, use of a certain list of modules only, ...)?

**Comment by SharmilaGoedhart** [comment]
I have already queried @sratcliffe about this. For the proposal submission, downloading the notebook as pdf is fine - it is now quite compact.

It may be necessary to instruct the user to download and run the notebook themselves if you want the csv file with the pointings.

**Comment by gigjozsa** [comment]
@SharmilaGoedhart @spassmoor @vasaantk 

MeerKAT_Mosaic_Calculator.ipynb andMeerKAT_Mosaic_Calculator_base.py have been updated:
- It is not an error any more if the fpdf module is not available. If the summary output gets requested it will be suppressed with a cautioning to install fpdf. The warning will not be issued in the (unchanged) default version of the notebook because of the next point.
- Added an ``online`` switch/parameter optionally suppressing all output, which is the default status.

If I could get a system variable or similar indicating if we are online or not, the online switch could be removed and replaced by an automated recognition whether the notebook is run online or not. Please tell me or leave as it is.

**Review by spassmoor — APPROVED** [review]
This looks good

**Pull request merged**
