### PR TITLE
This is to fix a typo and remove confusing lines

### PR DESCRIPTION
**Pull request by spassmoor**
I have fixed a typo and removed unneeded lines 
Could you have a look through and make sure the calculation is sensible.

Thanks

### CODE REVIEW

**Review by gigjozsa — CHANGES_REQUESTED** [review]
I think this has been submitted without restarting the kernel. Could you please check?

**Comment by spassmoor** [comment]
Yes the kernel was restarted and rerun before the code was  committed

**Comment by spassmoor** [comment]
@gigjozsa  do you have any comments on the notebook ?

**Review by gigjozsa — APPROVED** [review]

**Comment by gigjozsa** [comment]
Nope, beautiful. If we do any better, we need to get it past an IP check. :)

**Comment by foxmouldy** [comment]
Can I just approve this pull request and move onto testing?

**Comment by gigjozsa** [comment]
Wait, just a moment.

**Comment by spassmoor** [comment]
I have reverted the change

**Comment by spassmoor** [comment]
I will make a new pull request @gigjozsa

**Pull request merged**
