### PR TITLE
Pimped up MeerKAT Mosaic Calculator

### PR DESCRIPTION
**Pull request by gigjozsa**
- Highlighted parameters in the description using Markdown
- Moved most code into a module MeerKAT_Mosaic_Calculator_base.py
- Added output pdf summary

### CODE REVIEW

**Comment by gigjozsa** [comment]
I have left the old mosaic calculator as MeerKAT_Mosaic_Calculator_old.ipynb . Please tell me when to remove it or remove it yourself.

**Comment by gigjozsa** [comment]
@foxmouldy @vasaantk @SharmilaGoedhart @spassmoor is this ok? Obviously, the user has to put the python script MeerKAT_Mosaic_Calculator_base.py in the same directory as the notebook, but this is hopefully clear to notebook users.

**Comment by gigjozsa** [comment]
@foxmouldy your suggestions are incorporated. Approve?

**Comment by foxmouldy** [comment]
New edits look good. Let's merge and test again.

**Pull request merged**
